apiVersion: apps/v1
kind: Deployment
metadata:
  name: kaviuln-app-2
  labels:
    app: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
        - name: myapp-container
          image: gcr.io/sit737-23t1-hossain-c94cda1/kaviuln/test-image:latest
          ports:
            - containerPort: 8080
